os:
  - linux

language: python

python:
  - '2.7'

sudo: required

privileged: true

services:
  - docker

cache:
  directories:
    - node_modules
    - $HOME/google-cloud-sdk/
    - __pycache__
    - app/__pycache__

notifications:
  email: false

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
  - openssl aes-256-cbc -K $encrypted_8f789aaec97f_key -iv $encrypted_8f789aaec97f_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d

script:
  - make Dockerfile.db
  - make Dockerfile.server
  - make start-db
  - sleep 8
  - make test
  - cat tests.tmp

after_success:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - tar -xzf credentials.tar.gz
  - gcloud version
  - bash ./scripts/gcloud-auth.sh
  - bash ./scripts/gcloud-deploy.sh