FORMAT: 1A
HOST: http://glmarous.me/

# glamrous.me

Glamrous has a simple API that lets you get information all your favorite makeup items.

## Products Collection [/product]

### List All Products [GET]

+ Response 200 (application/json)

        [
          {
            "brand": {
              "id": 1, 
              "name": "pure anada"
            }, 
            "brand_id": 1, 
            "category": {
              "id": 1, 
              "name": "mascara"
            }, 
            "colors": [
              {
                "hashcode": "#3E2829", 
                "id": 1, 
                "name": "Brown "
              }, 
              {
                "hashcode": "#000000", 
                "id": 2, 
                "name": "Black "
              }
            ], 
            "description": "Finally, a natural mascara you can feel good about putting on your lashes!\nIt is naturally paraben-free, gluten-free, and mercury-free. \nYou will be amazed at how well this mascara builds volume and length to your lashes.\nThis is the natural mascara you\u2019", 
            "id": 1, 
            "image_url": "https://d3t32hsnjxo7q6.cloudfront.net/i/afefede002b8d94f6e53ea07dd4070f9_ra,w158,h184_pa,w158,h184.jpg", 
            "name": "Pure Anada Natural Mascara", 
            "price": 14.0, 
            "rating": 4.6, 
            "tags": [
              {
                "id": 1, 
                "name": "Canadian"
              }, 
              {
                "id": 2, 
                "name": "Gluten Free"
              }, 
              {
                "id": 3, 
                "name": "Natural"
              }
            ]
          }, 
          {
            "brand": {
              "id": 1, 
              "name": "pure anada"
            }, 
            "brand_id": 1, 
            "category": {
              "id": 7, 
              "name": "bronzer"
            }, 
            "colors": [
              {
                "hashcode": "#FFFFFF", 
                "id": 1726, 
                "name": "Earth "
              }
            ], 
            "description": "Impart a healthy glow, with a Pure Anada luminous mineral bronzer!Shade Range:Ingredients: Mica,\u00a0 Iron Oxides, Ultramarines, May contain: Titanium Dioxide", 
            "id": 2, 
            "image_url": "https://d3t32hsnjxo7q6.cloudfront.net/i/01195de6de1092125f703c5662d99af9_ra,w158,h184_pa,w158,h184.jpeg", 
            "name": "Pure Anada Loose Mineral Luminous Bronzer", 
            "price": 12.0, 
            "rating": 5.0, 
            "tags": [
              {
                "id": 1, 
                "name": "Canadian"
              }, 
              {
                "id": 3, 
                "name": "Natural"
              }
            ]
          }
        ]

## Product Collection [/product/{product_id}]

+ Parameters
    + product_id (number) - ID of the product in the form of an integer

### List Information of Product [GET]

+ Response 200 (application/json)

        {
          "brand": {
            "id": 1, 
            "name": "pure anada"
          }, 
          "brand_id": 1, 
          "category": {
            "id": 1, 
            "name": "mascara"
          }, 
          "colors": [
            {
              "hashcode": "#3E2829", 
              "id": 1, 
              "name": "Brown "
            }, 
            {
              "hashcode": "#000000", 
              "id": 2, 
              "name": "Black "
            }
          ], 
          "description": "Finally, a natural mascara you can feel good about putting on your lashes!\nIt is naturally paraben-free, gluten-free, and mercury-free. \nYou will be amazed at how well this mascara builds volume and length to your lashes.\nThis is the natural mascara you\u2019ve been waiting for!Ingredients: Aqua (Water), Oryza Sativa Wax (Rice Bran Wax), Olea Europea fruit oil \n(Olive Oil), Vegetable Source Cetyl Alcohol (Coconut), Coernica Cerifera\n (Carnauba Wax), Euphorbia Cerifera (Candelilla Wax), Vegetable \nGlycerin, Stearic Acid, Acacia Gum, Black Iron oxide (CI 77499),\u00a0 \nAminomethyl Popandiol (Ph Adjuster), Phenoxyethanol (Preservative).", 
          "id": 1, 
          "image_url": "https://d3t32hsnjxo7q6.cloudfront.net/i/afefede002b8d94f6e53ea07dd4070f9_ra,w158,h184_pa,w158,h184.jpg", 
          "name": "Pure Anada Natural Mascara", 
          "price": 14.0, 
          "rating": 4.6, 
          "tags": [
            {
              "id": 1, 
              "name": "Canadian"
            }, 
            {
              "id": 2, 
              "name": "Gluten Free"
            }, 
            {
              "id": 3, 
              "name": "Natural"
            }
          ]
        }
            
## Brands Collection [/brand]

### List All Brands [GET]

+ Response 200 (application/json)

        [
            {
                "avg_price": 14.27, 
                "avg_rating": 4.15, 
                "categories": [
                  {
                    "id": 1, 
                    "name": "mascara"
                  }, 
                  {
                    "id": 7, 
                    "name": "bronzer"
                  }, 
                  {
                    "id": 2, 
                    "name": "nail_polish"
                  }, 
                  {
                    "id": 4, 
                    "name": "eyeliner"
                  }, 
                  {
                    "id": 8, 
                    "name": "blush"
                  }, 
                  {
                    "id": 6, 
                    "name": "foundation"
                  }, 
                  {
                    "id": 9, 
                    "name": "eyeshadow"
                  }, 
                  {
                    "id": 3, 
                    "name": "lipstick"
                  }
                ], 
                "id": 1, 
                "image_url": "http://www.bing.com/cr?IG=9E6042FAB29E48619367089D0427BD32&CID=28BE60F4916B6E4A0A7A6AA890FB6F86&rd=1&h=a8eL8rF95Twk30Yzc1lFgq1VF1iquIdc0O42B7TPsTk&v=1&r=http%3a%2f%2fgenerationgreenwpg.com%2fwp-content%2fuploads%2f2016%2f02%2fPure-Anada-logo-300x149.jpg&p=DevEx,5008.1", 
                "name": "pure anada", 
                "num_products": 16, 
                "tags": [
                  {
                    "id": 1, 
                    "name": "Canadian"
                  }, 
                  {
                    "id": 2, 
                    "name": "Gluten Free"
                  }, 
                  {
                    "id": 3, 
                    "name": "Natural"
                  }, 
                  {
                    "id": 4, 
                    "name": "Vegan"
                  }, 
                  {
                    "id": 7, 
                    "name": "Non-GMO"
                  }, 
                  {
                    "id": 6, 
                    "name": "Peanut Free Product"
                  }
                ]
              }
        ]


## Category Collection [/category]

### List All Categories [GET]

+ Response 200 (application/json)

        [
            {
                "avg_price": 14.03, 
                "avg_rating": 3.02, 
                "id": 1, 
                "name": "mascara", 
                "num_products": 69
              }
        ]
            
## Tags Collection [/tag]

### List All Tags [GET]

+ Response 200 (application/json)

        [
            {
                "avg_price": 17.77, 
                "avg_rating": 2.97, 
                "brands": [
                  {
                    "id": 1, 
                    "name": "pure anada"
                  }, 
                  {
                    "id": 8, 
                    "name": "earth lab"
                  }, 
                  {
                    "id": 9, 
                    "name": "suncoat"
                  }, 
                  {
                    "id": 16, 
                    "name": "marcelle"
                  }, 
                  {
                    "id": 17, 
                    "name": "zorah"
                  }, 
                  {
                    "id": 21, 
                    "name": "dalish"
                  }, 
                  {
                    "id": 32, 
                    "name": "moov"
                  }, 
                  {
                    "id": 38, 
                    "name": "mistura"
                  }, 
                  {
                    "id": 40, 
                    "name": "saint cosmetics"
                  }
                ], 
                "id": 1, 
                "name": "Canadian", 
                "num_products": 51
              }
        ]