FORMAT: 1A
HOST: http://glmarous.me/

# glamrous.me

Glamrous has a simple API that lets you get information all your favorite makeup items.

## Products Collection [/products]

### List All Products [GET]

+ Response 200 (application/json)

        [
          {
            "description": "One innovative product, two ways to double the impact of your unique eye color! Simply smooth the silky, weightless liquid over lids for a shimmering splash of eye-enhancing color, or top with powder shadow for an even bolder, longer lasting look. Either way, feel confident knowing that the built-in primer ensures that the multi-dimensional finish won’t crease, fade, or smudge all day!How to Use: Apply to the inner corner of the lid and blend outwards using fingers. Apply more for a bolder pop of color, or layer under your favorite intense i-color shadow kit for an even more intense look.",
            "id": 1,
            "image_url": "https://d3t32hsnjxo7q6.cloudfront.net/i/757cf4197fe84ed9c1e2c21ed63d1be3_ra,w158,h184_pa,w158,h184.jpeg",
            "name": "Almay Intense i-Color Liquid Shadow + Color Primer",
            "price": 10.99,
            "rating": 4.50,
            "brand":
                {
                    "name": "almay",
                    "id": 1
                },
            "colors": [
                {
                    "hashcode": "#000000",
                    "name": "Black",
                    "id": 1
                }
            ],
            "tags": [
                {
                    "id": 1,
                    "name": "Organic"
                }
            ],
            "category": {
                "id": 1,
                "name": "eyeshadow"
            },
            "sub_category": {
                "id": 1,
                "name": "pencil"
            }
            },
            {
                "description": "Almay Smart Shade™ makeup makes it easy to find “the one” with just three skintone-adjusting shades to choose from, not hundreds! It adjusts to the natural tones and nuances of your skin with breakthrough new Almay ToneMimic™ shade-sensing bead technology which intuitively transforms to your skintone for all day natural looking coverage in your perfect shade. Contains broad spectrum SPF 15. HYPOALLERGENIC. DERMATOLOGIST TESTED. MADE FOR SENSITIVE SKIN.Shade Range:",
                "id": 2,
                "image_url": "https://d3t32hsnjxo7q6.cloudfront.net/i/afcbd92c05ea8b6452eabc80e2b9d549_ra,w158,h184_pa,w158,h184.jpeg",
                "name": "Almay Smart Shade Skintone Matching Makeup",
                "price": 17.29,
                "rating": 4.50,
                "brand": {
                    "name": "almay",
                    "id": 1
                },
                "colors": [
                    {
                        "hashcode": "#A0522D",
                        "id": 1
                    }
                ],
                "tags": [
                    {
                        "id": 1,
                        "name": "Organic"
                    }
                ],
                "category": {
                    "id": 1,
                    "name": "foundation"
                },
                "sub_category":{
                    "id": 1,
                    "name": "liquid"
                }
                
            }
          
        ]

## Product Collection [/products/{product_id}]

+ Parameters
    + product_id (number) - ID of the product in the form of an integer

### List Information of Product [GET]

+ Response 200 (application/json)

        {
          "description": "Play up your eye color with dramatic contrasting color! Define your eyes with bold color. Comes with a precision tip applicator so you can smoothly and easily create a high impact look. Features: Hypoallergenic non-irritating Ophthalmologist Clinically and allergy tested Suitable for contact lens wearers",
          "id": 1,
          "image_url":"https://d3t32hsnjxo7q6.cloudfront.net/i/6cf30fccb626b5b1eacc9db7b29dc6c2_ra,w158,h184_pa,w158,h184.jpeg",
          "name":"Almay Intense i-Colour Play Up Liquid Liner",
          "price": 10.99,
          "rating": 4.00,
          "brand": {
            "name": "almay",
            "id": 1
          },
          "category":
            {
                "id": 1,
                "name": "eyeliner"
            },
          "colors":
            [ 
                {
                    "hashcode":"#D3D3D3",
                    "name": "lightgray",
                    "id": 1
                }
            ],
            "sub_category": 
                {
                    "id": 1,
                    "name": "liquid"
                },
            "tags":
                [
                    {
                        "id": 1,
                        "name": "Canadian"
                    }
                ]
        }
            
## Brands Collection [/brands]

### List All Brands [GET]

+ Response 200 (application/json)

        [
            {
                "avg_price": 14.27, 
                "avg_rating": 4.15, 
                "categories": [
                  {
                    "id": 1, 
                    "name": "mascara"
                  }, 
                  {
                    "id": 7, 
                    "name": "bronzer"
                  }, 
                  {
                    "id": 2, 
                    "name": "nail_polish"
                  }, 
                  {
                    "id": 4, 
                    "name": "eyeliner"
                  }, 
                  {
                    "id": 8, 
                    "name": "blush"
                  }, 
                  {
                    "id": 6, 
                    "name": "foundation"
                  }, 
                  {
                    "id": 9, 
                    "name": "eyeshadow"
                  }, 
                  {
                    "id": 3, 
                    "name": "lipstick"
                  }
                ], 
                "id": 1, 
                "image_url": "http://www.bing.com/cr?IG=9E6042FAB29E48619367089D0427BD32&CID=28BE60F4916B6E4A0A7A6AA890FB6F86&rd=1&h=a8eL8rF95Twk30Yzc1lFgq1VF1iquIdc0O42B7TPsTk&v=1&r=http%3a%2f%2fgenerationgreenwpg.com%2fwp-content%2fuploads%2f2016%2f02%2fPure-Anada-logo-300x149.jpg&p=DevEx,5008.1", 
                "name": "pure anada", 
                "num_products": 16, 
                "tags": [
                  {
                    "id": 1, 
                    "name": "Canadian"
                  }, 
                  {
                    "id": 2, 
                    "name": "Gluten Free"
                  }, 
                  {
                    "id": 3, 
                    "name": "Natural"
                  }, 
                  {
                    "id": 4, 
                    "name": "Vegan"
                  }, 
                  {
                    "id": 7, 
                    "name": "Non-GMO"
                  }, 
                  {
                    "id": 6, 
                    "name": "Peanut Free Product"
                  }
                ]
              }
        ]

## Brand Collection [/brands/{brand_id}]

+ Parameters 
    + brand_id (number) - ID of the brand in the form of an integer

### List Information of Brand [GET]

+ Response 200 (application/json)

        {
            "avg_price": 12.79,
            "avg_rating": 3.60,
            "id": 1,
            "image_url": "http://www.logotypes101.com/logos/848/4EB2A4D7683533F8F80ABEFC588C22B0/Almay.png",
            "num_products": 14,
            "categories": [
                { 
                    "id": 1,    
                    "name": "eyeliner"
                },
                {
                    "id": 2,
                    "name": "lipstick"
                },
                {
                    "id": 3,
                    "name": "foundation"
                },
                {
                    "id": 4,
                    "name": "eyeshadow"
                },
                {
                    "id": 5,
                    "name": "blush"
                },
                {
                    "id": 6,
                    "name": "masacara"
                },
                {
                    "id": 7,
                    "name": "bronzer"
                }
            ],
            "products": [
                {
                    "id": 1,
                    "name": "Almay Smart Shade Anti-Aging Skintone Matching Makeup"
                },
                {
                    "id": 2,
                    "name": "Almay Smart Shade Skintone Matching Makeup"
                },
                {
                    "id": 3,
                    "name": "Almay Smart Shade Powder Bronzer"
                },
                {
                    "id": 4,
                    "name": "Almay Intense i-Color Volumizing Masacara"
                },
                {
                    "id": 5,
                    "name": "Almay One Coat Get Up & Grow Mascara"
                },
                {
                    "id": 6,
                    "name": "Almay Intense i-Color Liquid Shadow + Color Primer"
                },
                {
                    "id": 7,
                    "name": "Almay Intense i-Colour Play Up Liquid Liner"
                },
                {
                    "id": 8,
                    "name": "Almay Smart Shade Butter Kiss Lipstick"
                },
                {
                    "id": 9,
                    "name": "Almay One Coat Thickening Mascara"
                },
                {
                    "id": 10,
                    "name": "Almay Liquid Liner"
                },
                {
                    "id": 11,
                    "name": "Almay Intense i-Color Everyday Neutrals for Blue Eyes"
                },
                {
                    "id": 12,
                    "name": "Almay Smart Shade Powder Blush"
                },
                {
                    "id": 13,
                    "name": "Almay Intense i-Colour Bring Out Eyeliner"
                },
                {
                    "id": 14,
                    "name": "Almay Truly Lasting Color Makeup"
                }
            ],
            "sub_categories": [
                {
                    "id": 1,
                    "name": "powder"
                },
                {
                    "id": 2,
                    "name": "pencil"
                },
                {
                    "id": 3,
                    "name": "liquid"
                }
            ],
            "tags": [
            ]
        }

## Category Collection [/categories]

### List All Categories [GET]

+ Response 200 (application/json)

        [
            {
                "avg_price": 14.03, 
                "avg_rating": 3.02, 
                "id": 1, 
                "name": "mascara", 
                "num_products": 69
              }
        ]
            
## Tags Collection [/tags]

### List All Tags [GET]

+ Response 200 (application/json)

        [
            {
                "avg_price": 17.77, 
                "avg_rating": 2.97, 
                "brands": [
                  {
                    "id": 1, 
                    "name": "pure anada"
                  }, 
                  {
                    "id": 8, 
                    "name": "earth lab"
                  }, 
                  {
                    "id": 9, 
                    "name": "suncoat"
                  }, 
                  {
                    "id": 16, 
                    "name": "marcelle"
                  }, 
                  {
                    "id": 17, 
                    "name": "zorah"
                  }, 
                  {
                    "id": 21, 
                    "name": "dalish"
                  }, 
                  {
                    "id": 32, 
                    "name": "moov"
                  }, 
                  {
                    "id": 38, 
                    "name": "mistura"
                  }, 
                  {
                    "id": 40, 
                    "name": "saint cosmetics"
                  }
                ], 
                "id": 1, 
                "name": "Canadian", 
                "num_products": 51
              }
        ]