FORMAT: 1A
HOST: http://glmarous.me/

# glamrous.me

Glamrous has a simple API that lets you get information all your favorite makeup items.

## Products Collection [/product]

### List All Products [GET]

+ Response 200 (application/json)

        [
            {
                "product_id": 1,
                "brand_name": "Pure Anada", 
                "name": "Pure Anada Natural Mascara",
                "description": "Finally, a natural mascara you can feel good about putting on your lashes!\nIt is naturally paraben-free, gluten-free, and mercury-free. \nYou will be amazed at how well this mascara builds volume and length to your lashes.\nThis is the natural mascara you’ve been waiting for!Ingredients: Aqua (Water), Oryza Sativa Wax (Rice Bran Wax), Olea Europea fruit oil \n(Olive Oil), Vegetable Source Cetyl Alcohol (Coconut), Coernica Cerifera\n (Carnauba Wax), Euphorbia Cerifera (Candelilla Wax), Vegetable \nGlycerin, Stearic Acid, Acacia Gum, Black Iron oxide (CI 77499),  \nAminomethyl Popandiol (Ph Adjuster), Phenoxyethanol (Preservative).",
                "price": "14.0",
                "rating": 4.6,
                "product_type": "Mascara",
                "image_link": "https://d3t32hsnjxo7q6.cloudfront.net/i/afefede002b8d94f6e53ea07dd4070f9_ra,w158,h184_pa,w158,h184.jpg",
                "product_colors": [
                  {
                    "hex_color": "#3E2829",
                    "color_name": "Brown "
                  },
                  {
                    "hex_color": "#000000",
                    "color_name": "Black "
                  }
                ],
                "tag_list": [
                  "Canadian",
                  "Gluten Free",
                  "Natural"
                ]
            }, 
            {
                "product_id": 2,
                "brand_name": "Pure Anada", 
                "name": "Pure Anada Natural Mascara 2",
                "description": "Finally, a natural mascara you can feel good about putting on your lashes!\nIt is naturally paraben-free, gluten-free, and mercury-free. \nYou will be amazed at how well this mascara builds volume and length to your lashes.\nThis is the natural mascara you’ve been waiting for!Ingredients: Aqua (Water), Oryza Sativa Wax (Rice Bran Wax), Olea Europea fruit oil \n(Olive Oil), Vegetable Source Cetyl Alcohol (Coconut), Coernica Cerifera\n (Carnauba Wax), Euphorbia Cerifera (Candelilla Wax), Vegetable \nGlycerin, Stearic Acid, Acacia Gum, Black Iron oxide (CI 77499),  \nAminomethyl Popandiol (Ph Adjuster), Phenoxyethanol (Preservative).",
                "price": "14.0",
                "rating": 4.6,
                "product_type": "Mascara",
                "image_link": "https://d3t32hsnjxo7q6.cloudfront.net/i/afefede002b8d94f6e53ea07dd4070f9_ra,w158,h184_pa,w158,h184.jpg",
                "product_colors": [
                  {
                    "hex_color": "#3E2829",
                    "color_name": "Brown "
                  },
                  {
                    "hex_color": "#000000",
                    "color_name": "Black "
                  }
                ],
                "tag_list": [
                  "Canadian",
                  "Gluten Free",
                  "Natural"
                ]
            }
        ]

## Product Collection [/product/{product_id}]

+ Parameters
    + product_id (number) - ID of the product in the form of an integer

### List Information of Product [GET]

+ Response 200 (application/json)

        {
            "product_id": 1,
            "brand_name": "Pure Anada", 
            "name": "Pure Anada Natural Mascara",
            "description": "Finally, a natural mascara you can feel good about putting on your lashes!\nIt is naturally paraben-free, gluten-free, and mercury-free. \nYou will be amazed at how well this mascara builds volume and length to your lashes.\nThis is the natural mascara you’ve been waiting for!Ingredients: Aqua (Water), Oryza Sativa Wax (Rice Bran Wax), Olea Europea fruit oil \n(Olive Oil), Vegetable Source Cetyl Alcohol (Coconut), Coernica Cerifera\n (Carnauba Wax), Euphorbia Cerifera (Candelilla Wax), Vegetable \nGlycerin, Stearic Acid, Acacia Gum, Black Iron oxide (CI 77499),  \nAminomethyl Popandiol (Ph Adjuster), Phenoxyethanol (Preservative).",
            "price": "14.0",
            "rating": 4.6,
            "product_type": "Mascara",
            "image_link": "https://d3t32hsnjxo7q6.cloudfront.net/i/afefede002b8d94f6e53ea07dd4070f9_ra,w158,h184_pa,w158,h184.jpg",
            "product_colors": [
              {
                "hex_color": "#3E2829",
                "color_name": "Brown "
              },
              {
                "hex_color": "#000000",
                "color_name": "Black "
              }
            ],
            "tag_list": [
              "Canadian",
              "Gluten Free",
              "Natural"
            ]
        }
            
## Brands Collection [/brand]

### List All Brands [GET]

+ Response 200 (application/json)

        [
            {
                "brand_id": 1,
                "brand_name": "Pure Anada", 
                "avg_price": 4.20,
                "avg_rating": 4.2,
                "num_products": 2,
                "image_link": "https://d3t32hsnjxo7q6.cloudfront.net/i/afefede002b8d94f6e53ea07dd4070f9_ra,w158,h184_pa,w158,h184.jpg",
                "products": [
                  {
                    "product_id": 1,
                    "product_name": "Pure Anada Natural Mascara"
                  },
                  {
                    "product_id": 2,
                    "product_name": "Pure Anada Natural Bronzer "
                  }
                ]
            }
        ]
        

## Colors Collection [/color]

### List All Colors [GET]

+ Response 200 (application/json)

        [
            {
                "color_id": 420,
                "color_name": "seaWeed Green", 
                "color_hashcode": "#536633",
                "num_products": 420 
            }
        ]


## Category Collection [/category]

### List All Categories [GET]

+ Response 200 (application/json)

        [
            {
                "category_id": 1,
                "category_name": "Generic Name", 
                "avg_price": 14.0,
                "avg_rating": 4.6,
                "num_products": 2,
                "products": [
                    {
                        "product_id": 1,
                        "brand_name": "Pure Anada",
                        "product_name": "Pure Anada Natural Mascara"
                    }, {
                        "product_id": 4,
                        "brand_name": "Generic Company",
                        "product_name": "Generic Mascara"
                    }
                    
                ]
            }
        ]
        
## Sub-Category Collection [/sub_category]

### List All Sub-Categories [GET]

+ Response 200 (application/json)

        [
            {
                "sub_category_id": 1,
                "sub_category_name": "Generic Name", 
                "avg_price": 14.0,
                "avg_rating": 4.6,
                "num_products": 2,
                "products": [
                    {
                        "product_id": 1,
                        "brand_name": "Pure Anada",
                        "product_name": "Pure Anada Natural Mascara"
                    }, {
                        "product_id": 4,
                        "brand_name": "Generic Company",
                        "product_name": "Generic Mascara"
                    }
                    
                ]
            }
        ]
            
## Tags Collection [/tag]

### List All Tags [GET]

+ Response 200 (application/json)

        [
            {
                "tag_id": 1,
                "tag_name": "Generic Tag", 
                "avg_price": 12.0,
                "avg_rating": 4.0,
                "num_products": 2,
                "products": [
                    {
                        "product_id": 1,
                        "brand_name": "Pure Anada",
                        "product_name": "Pure Anada Natural Mascara"
                    }, {
                        "product_id": 4,
                        "brand_name": "Generic Company",
                        "product_name": "Generic Mascara"
                    }
                    
                ]
            }
        ]



