FROM alpine:3.3

RUN apk add --update && \
	apk add --no-cache \
		bash \
		nodejs \
		python3 \
		tmux && \
	ln -s /usr/bin/python3 /usr/bin/python

RUN python -m ensurepip && \
	ln -s /usr/bin/pip3 /usr/bin/pip && \
	pip install --upgrade pip && \
	pip install \
		autopep8 \
		coverage \
		pylint

RUN npm install -g \
	rollup
