version: '2'

services:
  app:
    restart: always
    build: .
    volumes:
      - .:/usr/web:rw
    expose:
      - "5000"
    ports:
      - "8080:5000"
    command: python run_server.py
    depends_on:
      - postgres

  data:
    image: postgres:9.6
    volumes:
      - /var/lib/postgresql
    command: "true"

  postgres:
    restart: always
    build: ./postgres
    volumes_from:
      - data
    ports:
      - "5432:5432"
