FROM python:3.6.0

RUN pip install --upgrade pip && \
	pip install \
		flask \
		Flask-Migrate \
		Flask-SQLAlchemy

RUN apt-get update && \
	apt-get install -y --no-install-recommends \
		libpq-dev \

EXPOSE 5000
