FROM alpine:3.3

RUN apk add --update && \
	apk add --no-cache \
		libpq \
		python3 && \
	ln -s /usr/bin/python3 /usr/bin/python

RUN python -m ensurepip && \
	ln -s /usr/bin/pip3 /usr/bin/pip && \
	pip install --upgrade pip && \
	pip install \
		flask \
		Flask-Migrate \
		Flask-SQLAlchemy

EXPOSE 5000
