FROM python:3.5.3-slim

RUN apt-get update && apt-get install -y libpq-dev gcc build-essential

RUN ls /usr/bin

RUN ln -s /usr/bin/python3 /usr/bin/python

RUN python -m ensurepip && \
	ln -s /usr/bin/pip3 /usr/bin/pip && \
	pip install --upgrade pip && \
	pip install \
		flask \
		Flask-SQLAlchemy \
		requests \
		psycopg2 \
		pylint \
		coverage

EXPOSE 5000
